<?php

declare(strict_types=1);

namespace App\Services;

use App\Core\Config;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception as MailerException;

/**
 * Sends transactional emails via PHPMailer + SMTP.
 *
 * Credentials are read from the environment: SMTP_HOST, SMTP_PORT,
 * SMTP_USER, SMTP_PASS, SMTP_FROM_EMAIL, and SMTP_FROM_NAME. When any
 * required value is absent, {@see send()} returns a failure result
 * immediately without attempting a connection.
 *
 * All methods are static; this class is never instantiated.
 *
 * @see https://github.com/PHPMailer/PHPMailer
 */
final class MailService
{
    /** Prevent instantiation — all access is via static methods. */
    private function __construct() {}

    /**
     * Sends an HTML email with a plain-text fallback.
     *
     * Configures PHPMailer with SMTP credentials from the environment,
     * attaches both the HTML and plain-text bodies, then attempts delivery.
     * When $textBody is empty it is auto-generated by stripping HTML tags
     * from $htmlBody.
     *
     * @param string $to        Recipient email address.
     * @param string $toName    Recipient display name (may be empty).
     * @param string $subject   Email subject line.
     * @param string $htmlBody  HTML body of the email.
     * @param string $textBody  Plain-text fallback; auto-stripped from HTML when empty.
     *
     * @return array{success: bool, error: ?string}
     *         On success: ['success' => true, 'error' => null].
     *         On failure: ['success' => false, 'error' => '…description…'].
     *
     * @example
     *   $result = MailService::send(
     *       'rosa@example.com',
     *       'Rosa García',
     *       'Your quote is ready!',
     *       MailService::buildHtml('<p>Here is your quote…</p>')
     *   );
     *   if (!$result['success']) { error_log($result['error']); }
     */
    public static function send(
        string $to,
        string $toName,
        string $subject,
        string $htmlBody,
        string $textBody = '',
    ): array {
        if (!self::isConfigured()) {
            return ['success' => false, 'error' => 'SMTP not configured'];
        }

        if ($textBody === '') {
            $textBody = strip_tags($htmlBody);
        }

        $mail = new PHPMailer(exceptions: true);

        try {
            $mail->isSMTP();
            $mail->CharSet    = 'UTF-8';
            $mail->Host       = (string) Config::get('SMTP_HOST', '');
            $mail->SMTPAuth   = true;
            $mail->Username   = (string) Config::get('SMTP_USER', '');
            $mail->Password   = (string) Config::get('SMTP_PASS', '');
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port       = (int) Config::get('SMTP_PORT', 587);

            $mail->setFrom(
                (string) Config::get('SMTP_FROM_EMAIL', ''),
                (string) Config::get('SMTP_FROM_NAME',  ''),
            );

            $mail->addAddress($to, $toName);

            $mail->isHTML(true);
            $mail->Subject = $subject;
            $mail->Body    = $htmlBody;
            $mail->AltBody = $textBody;

            $mail->send();

            return ['success' => true, 'error' => null];

        } catch (MailerException $e) {
            return ['success' => false, 'error' => $mail->ErrorInfo];
        }
    }

    /**
     * Returns true if the minimum required SMTP credentials are present.
     *
     * Checks that SMTP_HOST, SMTP_USER, SMTP_PASS, and SMTP_FROM_EMAIL are
     * all non-empty environment values.
     *
     * @return bool True when SMTP is configured and send() can attempt delivery.
     *
     * @example
     *   if (MailService::isConfigured()) { MailService::send(...); }
     */
    public static function isConfigured(): bool
    {
        return Config::get('SMTP_HOST',       '') !== ''
            && Config::get('SMTP_USER',       '') !== ''
            && Config::get('SMTP_PASS',       '') !== ''
            && Config::get('SMTP_FROM_EMAIL', '') !== '';
    }

    /**
     * Wraps $content in a branded HTML email template.
     *
     * Produces a self-contained inline-styled HTML document suitable for
     * passing directly to {@see send()} as $htmlBody. The template uses the
     * business name from BUSINESS_NAME config, a dark header (#0D0D0D),
     * the primary brand colour for the heading, a white content card, and a
     * muted footer.
     *
     * @param string $content The inner HTML to place in the content card,
     *                        e.g. '<p>Your quote has been sent…</p>'.
     *
     * @return string Complete HTML string ready to send as an email body.
     *
     * @see self::send()
     *
     * @example
     *   $html = MailService::buildHtml('<p>Hi Rosa, your deposit is confirmed!</p>');
     *   MailService::send('rosa@example.com', 'Rosa', 'Deposit Confirmed', $html);
     */
    public static function buildHtml(string $content): string
    {
        $businessName = htmlspecialchars((string) Config::get('BUSINESS_NAME', 'Perla\'s Flowers'));
        $primaryColor = htmlspecialchars((string) Config::get('COLOR_PRIMARY', '#B55AA0'));

        return <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{$businessName}</title>
        </head>
        <body style="margin:0; padding:0; background:#f4f4f4; font-family:Arial,Helvetica,sans-serif">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
                 style="background:#f4f4f4; padding:32px 16px">
            <tr>
              <td align="center">
                <table role="presentation" width="100%" style="max-width:600px">

                  <!-- Header -->
                  <tr>
                    <td style="background:#0D0D0D; border-radius:8px 8px 0 0; padding:28px 32px; text-align:center">
                      <h1 style="margin:0; font-family:Georgia,serif; font-size:1.6rem;
                                 font-weight:400; color:{$primaryColor}; letter-spacing:0.04em">
                        {$businessName}
                      </h1>
                    </td>
                  </tr>

                  <!-- Content card -->
                  <tr>
                    <td style="background:#ffffff; padding:32px; border-radius:0 0 8px 8px;
                               color:#1a1a1a; font-size:0.95rem; line-height:1.6">
                      {$content}
                    </td>
                  </tr>

                  <!-- Footer -->
                  <tr>
                    <td style="padding:20px 0; text-align:center;
                               color:#999; font-size:0.78rem; line-height:1.5">
                      &copy; {$businessName}. All rights reserved.<br>
                      You are receiving this email because you have interacted with us.
                    </td>
                  </tr>

                </table>
              </td>
            </tr>
          </table>
        </body>
        </html>
        HTML;
    }
}
