<?php

declare(strict_types=1);

namespace App\Services;

use App\Core\Config;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception as MailerException;

/**
 * Sends transactional emails, preferring authenticated SMTP and falling back to
 * the local sendmail binary when SMTP is unusable.
 *
 * SMTP credentials are read from the environment: SMTP_HOST, SMTP_PORT,
 * SMTP_USER, SMTP_PASS, SMTP_FROM_EMAIL, and SMTP_FROM_NAME.
 *
 * The fallback exists because of a live defect on the production host: under
 * `apache2handler`, PHP cannot retrieve the peer certificate during the
 * STARTTLS handshake (`stream_socket_enable_crypto(): Could not get peer
 * certificate`), so every SMTP send from a web request fails while the
 * identical call from the PHP CLI succeeds. Handing the message to the local
 * MTA sidesteps TLS entirely and — unlike disabling peer verification — never
 * puts the SMTP password on the wire. SMTP is still attempted first so that
 * CLI and cron sends keep using authenticated submission, and so the service
 * recovers automatically if the host is ever fixed.
 *
 * All methods are static; this class is never instantiated.
 *
 * @see https://github.com/PHPMailer/PHPMailer
 */
final class MailService
{
    /** Transport identifier for authenticated SMTP submission. */
    public const TRANSPORT_SMTP = 'smtp';

    /** Transport identifier for handoff to the local sendmail binary. */
    public const TRANSPORT_SENDMAIL = 'sendmail';

    /** Prevent instantiation — all access is via static methods. */
    private function __construct() {}

    /**
     * Sends an HTML email with a plain-text fallback.
     *
     * Attempts each available transport in order — SMTP first when it is
     * configured, then local sendmail — and stops at the first success. When
     * $textBody is empty it is auto-generated by stripping HTML tags from
     * $htmlBody. A failed SMTP attempt is written to the error log before the
     * fallback runs, so a silently degraded transport is still traceable.
     *
     * @param string $to        Recipient email address.
     * @param string $toName    Recipient display name (may be empty).
     * @param string $subject   Email subject line.
     * @param string $htmlBody  HTML body of the email.
     * @param string $textBody  Plain-text fallback; auto-stripped from HTML when empty.
     *
     * @return array{success: bool, error: ?string, transport: ?string}
     *         On success: ['success' => true, 'error' => null, 'transport' => 'smtp'|'sendmail'].
     *         On failure: ['success' => false, 'error' => '…every transport's error…',
     *                      'transport' => null].
     *
     * @see self::canSend()
     *
     * @example
     *   $result = MailService::send(
     *       'rosa@example.com',
     *       'Rosa García',
     *       'Your quote is ready!',
     *       MailService::buildHtml('<p>Here is your quote…</p>')
     *   );
     *   if (!$result['success']) { error_log($result['error']); }
     *
     * @example
     *   // SMTP configured but unusable on this SAPI — the message still goes out:
     *   $result = MailService::send('rosa@example.com', '', 'Hi', '<p>Hi</p>');
     *   // ['success' => true, 'error' => null, 'transport' => 'sendmail']
     */
    public static function send(
        string $to,
        string $toName,
        string $subject,
        string $htmlBody,
        string $textBody = '',
    ): array {
        $transports = [];
        if (self::isConfigured()) {
            $transports[] = self::TRANSPORT_SMTP;
        }
        if (self::sendmailAvailable()) {
            $transports[] = self::TRANSPORT_SENDMAIL;
        }

        if ($transports === []) {
            return [
                'success'   => false,
                'error'     => 'No mail transport available (SMTP not configured, sendmail_path empty)',
                'transport' => null,
            ];
        }

        if ($textBody === '') {
            $textBody = strip_tags($htmlBody);
        }

        $errors = [];

        foreach ($transports as $transport) {
            // A fresh instance per attempt — a failed send leaves connection and
            // error state behind that would otherwise leak into the fallback.
            $mail = new PHPMailer(exceptions: true);

            try {
                if ($transport === self::TRANSPORT_SMTP) {
                    self::configureSmtp($mail, self::smtpSettings());
                } else {
                    self::configureSendmail($mail);
                }

                self::compose($mail, $to, $toName, $subject, $htmlBody, $textBody);
                $mail->send();

                return ['success' => true, 'error' => null, 'transport' => $transport];

            } catch (MailerException $e) {
                // ErrorInfo can carry raw bytes from a half-open TLS socket, which
                // would corrupt a log line or break json_encode() — keep it ASCII.
                $detail = preg_replace('/[^\x20-\x7E]/', '', $mail->ErrorInfo ?: $e->getMessage());
                $errors[$transport] = $transport . ': ' . $detail;

                if ($transport !== end($transports)) {
                    error_log('[MailService] ' . $errors[$transport] . ' — falling back');
                }
            }
        }

        return ['success' => false, 'error' => implode(' | ', $errors), 'transport' => null];
    }

    /**
     * Returns true when at least one transport is available to send with.
     *
     * Callers that guard on mail availability should use this rather than
     * {@see isConfigured()}, which reports only on SMTP and would suppress a
     * perfectly usable sendmail fallback.
     *
     * @return bool True when SMTP is configured or sendmail is available.
     *
     * @see self::isConfigured()
     * @see self::sendmailAvailable()
     *
     * @example
     *   if (MailService::canSend()) { MailService::send(...); }
     */
    public static function canSend(): bool
    {
        return self::isConfigured() || self::sendmailAvailable();
    }

    /**
     * Returns true if the minimum required SMTP credentials are present.
     *
     * Checks that SMTP_HOST, SMTP_USER, SMTP_PASS, and SMTP_FROM_EMAIL are
     * all non-empty environment values. This reports on configuration only —
     * it does not prove the host can complete an SMTP session.
     *
     * @return bool True when SMTP is configured and send() will attempt it.
     *
     * @see self::canSend()
     *
     * @example
     *   // True on the production host, yet web-request sends still fall back
     *   // to sendmail — configured is not the same as usable.
     *   MailService::isConfigured();
     */
    public static function isConfigured(): bool
    {
        return Config::get('SMTP_HOST',       '') !== ''
            && Config::get('SMTP_USER',       '') !== ''
            && Config::get('SMTP_PASS',       '') !== ''
            && Config::get('SMTP_FROM_EMAIL', '') !== '';
    }

    /**
     * Returns true when PHP has a local sendmail binary configured.
     *
     * Reads the `sendmail_path` INI setting, which holds the binary plus its
     * arguments (e.g. `/usr/sbin/sendmail -t -i`), and checks the binary
     * itself is executable. Shared hosts normally set this; it is empty on
     * most Windows installs.
     *
     * @return bool True when send() can fall back to sendmail.
     *
     * @see self::canSend()
     * @see self::sendmailBinary()
     *
     * @example
     *   MailService::sendmailAvailable(); // true on pair.com, false on stock Windows
     */
    public static function sendmailAvailable(): bool
    {
        $binary = self::sendmailBinary((string) ini_get('sendmail_path'));

        return $binary !== '' && is_executable($binary);
    }

    /**
     * Extract the binary from a `sendmail_path` INI value.
     *
     * The setting bundles the executable with its arguments, so the arguments
     * have to come off before the path can be tested for existence.
     *
     * @param string $sendmailPath Raw INI value, e.g. '/usr/sbin/sendmail -t -i'.
     *
     * @return string The binary path, or '' when the value holds no path.
     *
     * @see self::sendmailAvailable()
     *
     * @example
     *   MailService::sendmailBinary('/usr/sbin/sendmail -t -i'); // '/usr/sbin/sendmail'
     *   MailService::sendmailBinary('');                         // ''
     */
    public static function sendmailBinary(string $sendmailPath): string
    {
        $trimmed = trim($sendmailPath);
        if ($trimmed === '') {
            return '';
        }

        $binary = strtok($trimmed, " \t");

        return $binary === false ? '' : $binary;
    }

    /**
     * Configure a mailer for authenticated SMTP submission over STARTTLS.
     *
     * Split out from {@see send()} so the transport wiring can be asserted
     * without opening a network connection.
     *
     * @param PHPMailer $mail     Mailer to configure in place.
     * @param array{host: string, port: int, user: string, pass: string} $settings
     *        Connection settings, normally from {@see smtpSettings()}.
     *
     * @see self::configureSendmail()
     *
     * @example
     *   MailService::configureSmtp($mail, ['host' => 'mail.example.com',
     *       'port' => 587, 'user' => 'me@example.com', 'pass' => 'secret']);
     */
    public static function configureSmtp(PHPMailer $mail, array $settings): void
    {
        $mail->isSMTP();
        $mail->Host       = $settings['host'];
        $mail->SMTPAuth   = true;
        $mail->Username   = $settings['user'];
        $mail->Password   = $settings['pass'];
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port       = $settings['port'];
    }

    /**
     * Configure a mailer to hand the message to the local sendmail binary.
     *
     * No network connection, no TLS, and no credentials are involved — the
     * message is injected straight into the host's MTA queue.
     *
     * @param PHPMailer $mail Mailer to configure in place.
     *
     * @see self::configureSmtp()
     *
     * @example
     *   MailService::configureSendmail($mail); // $mail->Mailer === 'sendmail'
     */
    public static function configureSendmail(PHPMailer $mail): void
    {
        $mail->isSendmail();
    }

    /**
     * Read the SMTP connection settings from the environment.
     *
     * @return array{host: string, port: int, user: string, pass: string}
     *         Port defaults to 587 when SMTP_PORT is unset.
     */
    private static function smtpSettings(): array
    {
        return [
            'host' => (string) Config::get('SMTP_HOST', ''),
            'port' => (int)    Config::get('SMTP_PORT', 587),
            'user' => (string) Config::get('SMTP_USER', ''),
            'pass' => (string) Config::get('SMTP_PASS', ''),
        ];
    }

    /**
     * Apply the sender, recipient, subject, and bodies to a configured mailer.
     *
     * Transport-agnostic: called identically for every attempt in {@see send()}.
     *
     * @param PHPMailer $mail     Mailer with a transport already configured.
     * @param string    $to       Recipient email address.
     * @param string    $toName   Recipient display name (may be empty).
     * @param string    $subject  Email subject line.
     * @param string    $htmlBody HTML body.
     * @param string    $textBody Plain-text alternative body.
     */
    private static function compose(
        PHPMailer $mail,
        string $to,
        string $toName,
        string $subject,
        string $htmlBody,
        string $textBody,
    ): void {
        $mail->CharSet = 'UTF-8';

        $mail->setFrom(
            (string) Config::get('SMTP_FROM_EMAIL', ''),
            (string) Config::get('SMTP_FROM_NAME',  ''),
        );

        $mail->addAddress($to, $toName);

        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body    = $htmlBody;
        $mail->AltBody = $textBody;
    }

    /**
     * Wraps $content in a branded HTML email template.
     *
     * Produces a self-contained inline-styled HTML document suitable for
     * passing directly to {@see send()} as $htmlBody. The template uses the
     * business name from BUSINESS_NAME config, a dark header (#0D0D0D),
     * the primary brand colour for the heading, a white content card, and a
     * muted footer.
     *
     * @param string $content The inner HTML to place in the content card,
     *                        e.g. '<p>Your quote has been sent…</p>'.
     *
     * @return string Complete HTML string ready to send as an email body.
     *
     * @see self::send()
     *
     * @example
     *   $html = MailService::buildHtml('<p>Hi Rosa, your deposit is confirmed!</p>');
     *   MailService::send('rosa@example.com', 'Rosa', 'Deposit Confirmed', $html);
     */
    public static function buildHtml(string $content): string
    {
        $businessName = htmlspecialchars((string) Config::get('BUSINESS_NAME', 'Perla\'s Flowers'));
        $primaryColor = htmlspecialchars((string) Config::get('COLOR_PRIMARY', '#B55AA0'));

        return <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{$businessName}</title>
        </head>
        <body style="margin:0; padding:0; background:#f4f4f4; font-family:Arial,Helvetica,sans-serif">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
                 style="background:#f4f4f4; padding:32px 16px">
            <tr>
              <td align="center">
                <table role="presentation" width="100%" style="max-width:600px">

                  <!-- Header -->
                  <tr>
                    <td style="background:#0D0D0D; border-radius:8px 8px 0 0; padding:28px 32px; text-align:center">
                      <h1 style="margin:0; font-family:Georgia,serif; font-size:1.6rem;
                                 font-weight:400; color:{$primaryColor}; letter-spacing:0.04em">
                        {$businessName}
                      </h1>
                    </td>
                  </tr>

                  <!-- Content card -->
                  <tr>
                    <td style="background:#ffffff; padding:32px; border-radius:0 0 8px 8px;
                               color:#1a1a1a; font-size:0.95rem; line-height:1.6">
                      {$content}
                    </td>
                  </tr>

                  <!-- Footer -->
                  <tr>
                    <td style="padding:20px 0; text-align:center;
                               color:#999; font-size:0.78rem; line-height:1.5">
                      &copy; {$businessName}. All rights reserved.<br>
                      You are receiving this email because you have interacted with us.
                    </td>
                  </tr>

                </table>
              </td>
            </tr>
          </table>
        </body>
        </html>
        HTML;
    }
}
