<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Pure, side-effect-free logic for the local service-area landing pages.
 *
 * Every method is static and operates only on the arrays it is handed (the
 * city data from config/local-areas.php and the service definitions from
 * config/local-services.php) plus scalar arguments. Nothing here touches the
 * database, session, environment, or output — which is exactly what makes the
 * SEO logic unit-testable without the live server. The thin loaders
 * {@see self::areas()} and {@see self::services()} are the only methods that
 * read the filesystem.
 *
 * @see \App\Controllers\LocalAreaController  The HTTP glue that renders these pages.
 * @see config/local-areas.php                The city/venue data this operates on.
 * @see config/local-services.php             The service definitions.
 */
final class LocalArea
{
    /**
     * Load the city data file (config/local-areas.php).
     *
     * @return array<string, array<string, mixed>> Cities keyed by slug.
     *
     * @example
     *   $areas = LocalArea::areas();
     *   $bixby = $areas['bixby'];
     */
    public static function areas(): array
    {
        /** @var array<string, array<string, mixed>> $data */
        $data = require dirname(__DIR__, 2) . '/config/local-areas.php';
        return $data;
    }

    /**
     * Load the service-definition file (config/local-services.php).
     *
     * @return array<string, array<string, mixed>> Services keyed by code.
     *
     * @example
     *   $services = LocalArea::services();
     *   $funeralPrefix = $services['funeral']['prefix']; // 'funeral-flowers'
     */
    public static function services(): array
    {
        /** @var array<string, array<string, mixed>> $data */
        $data = require dirname(__DIR__, 2) . '/config/local-services.php';
        return $data;
    }

    /**
     * Map a city-page service code to the occasion bouquet-page slug it links to.
     *
     * Drives the per-venue "Send flowers" link and the birthday inline grid:
     *   - funeral  → 'sympathy'
     *   - hospital → 'get-well' (the primary hospital occasion; new-baby is also
     *                hospital-related but the landing page is get-well)
     *   - birthday → 'birthday'
     *
     * @param string $service Service code: 'funeral' | 'hospital' | 'birthday'.
     *
     * @return string|null The occasion slug, or null for an unknown service.
     *
     * @example
     *   LocalArea::occasionSlugForService('funeral');  // 'sympathy'
     *   LocalArea::occasionSlugForService('hospital');  // 'get-well'
     *   LocalArea::occasionSlugForService('unknown');   // null
     */
    public static function occasionSlugForService(string $service): ?string
    {
        return [
            'funeral'  => 'sympathy',
            'hospital' => 'get-well',
            'birthday' => 'birthday',
        ][$service] ?? null;
    }

    /**
     * Load the geocoded venue-coordinate cache (config/local-areas-coords.php).
     *
     * Maps a venue's exact address string to its latitude/longitude. The cache
     * is generated by bin/geocode-local-areas.php; when it is absent (e.g. a
     * fresh checkout that has not been geocoded yet) an empty array is returned
     * and per-venue distances/fees are simply omitted from the page.
     *
     * @return array<string, array{lat: float, lng: float}> Coordinates by address.
     *
     * @example
     *   $coords = LocalArea::coords();
     *   $coords['6161 S Yale Ave, Tulsa, OK 74136'] ?? null;
     */
    public static function coords(): array
    {
        $file = dirname(__DIR__, 2) . '/config/local-areas-coords.php';
        if (!is_file($file)) {
            return [];
        }
        /** @var array<string, array{lat: float, lng: float}> $data */
        $data = require $file;
        return is_array($data) ? $data : [];
    }

    /**
     * Look up a city by its URL slug.
     *
     * @param string                              $slug  City slug, e.g. 'broken-arrow'.
     * @param array<string, array<string, mixed>> $areas City data (defaults to areas()).
     *
     * @return array<string, mixed>|null The city record, or null if unknown.
     *
     * @example
     *   LocalArea::cityBySlug('jenks', $areas)['name']; // 'Jenks'
     *   LocalArea::cityBySlug('atlantis', $areas);      // null
     */
    public static function cityBySlug(string $slug, array $areas): ?array
    {
        return $areas[$slug] ?? null;
    }

    /**
     * Build the page <title>/pageTitle for a service + city in a given language.
     *
     * @param string                $service  Service code ('funeral'|'hospital'|'birthday').
     * @param array<string, mixed>  $city     A city record from areas().
     * @param string                $lang     'en' or 'es'.
     * @param array<string, mixed>  $services Service definitions (defaults to services()).
     *
     * @return string The localized title, with the city name substituted.
     *
     * @example
     *   LocalArea::serviceTitle('funeral', $bixby, 'en', $services);
     *   // 'Funeral Flower Delivery to Bixby, OK'
     */
    public static function serviceTitle(string $service, array $city, string $lang, array $services): string
    {
        return self::fill($services[$service]['title_' . self::lang($lang)] ?? '%s', (string) $city['name']);
    }

    /**
     * Build the meta description for a service + city in a given language.
     *
     * @see self::serviceTitle() for parameter semantics.
     *
     * @return string The localized meta description, with the city name substituted.
     */
    public static function serviceMeta(string $service, array $city, string $lang, array $services): string
    {
        return self::fill($services[$service]['meta_' . self::lang($lang)] ?? '%s', (string) $city['name']);
    }

    /**
     * Build the hero headline (H1) for a service + city in a given language.
     *
     * @see self::serviceTitle() for parameter semantics.
     *
     * @return string The localized headline, with the city name substituted.
     */
    public static function serviceHeadline(string $service, array $city, string $lang, array $services): string
    {
        return self::fill($services[$service]['h1_' . self::lang($lang)] ?? '%s', (string) $city['name']);
    }

    /**
     * The localized heading for a service's venue list (null for birthday pages).
     *
     * @see self::serviceTitle() for parameter semantics.
     *
     * @return string|null The heading with the city name substituted, or null
     *                     when the service renders no venue list.
     */
    public static function venueHeading(string $service, array $city, string $lang, array $services): ?string
    {
        $tpl = $services[$service]['venue_heading_' . self::lang($lang)] ?? null;
        return $tpl === null ? null : self::fill((string) $tpl, (string) $city['name']);
    }

    /**
     * The named venues (funeral homes or hospitals) shown on a service + city page.
     *
     * @param string                $service  Service code.
     * @param array<string, mixed>  $city     A city record.
     * @param array<string, mixed>  $services Service definitions.
     *
     * @return list<array{name: string, address: string}> Venues, or [] when the
     *         service has no venue list (e.g. birthday) or the city has none.
     *
     * @example
     *   LocalArea::venues('hospital', $bixby, $services); // [['name'=>'Saint Francis…', …], …]
     *   LocalArea::venues('birthday', $bixby, $services); // []
     */
    public static function venues(string $service, array $city, array $services): array
    {
        $key = $services[$service]['entities'] ?? null;
        if (!is_string($key)) {
            return [];
        }
        /** @var list<array{name: string, address: string}> $list */
        $list = $city[$key] ?? [];
        return $list;
    }

    /**
     * Great-circle (straight-line) distance in miles between two coordinates.
     *
     * Mirrors the Haversine formula used by the order form's delivery-fee
     * calculator (views/public/order.php) exactly — including the Earth radius
     * of 3958.8 miles — so per-venue estimates on the landing pages match what
     * a customer would be quoted at checkout for the same coordinates.
     *
     * @param float $lat1 Latitude of point A, in degrees.
     * @param float $lng1 Longitude of point A, in degrees.
     * @param float $lat2 Latitude of point B, in degrees.
     * @param float $lng2 Longitude of point B, in degrees.
     *
     * @return float Distance in statute miles.
     *
     * @example
     *   LocalArea::haversineMiles(36.0814, -95.9987, 36.0814, -95.9987); // 0.0
     */
    public static function haversineMiles(float $lat1, float $lng1, float $lat2, float $lng2): float
    {
        $r    = 3958.8;
        $dLat = deg2rad($lat2 - $lat1);
        $dLng = deg2rad($lng2 - $lng1);
        $a    = sin($dLat / 2) ** 2
              + cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * sin($dLng / 2) ** 2;

        return $r * 2 * atan2(sqrt($a), sqrt(1 - $a));
    }

    /**
     * Delivery fee for a given distance, using the shop's tiered pricing.
     *
     * Mirrors the order form: a flat base fee covers everything inside the base
     * radius, then a per-mile surcharge applies to each mile beyond it. The
     * result is rounded to whole cents.
     *
     * @param float $miles     Straight-line distance from the studio, in miles.
     * @param float $baseMiles Radius covered by the flat base fee.
     * @param float $baseFee   Flat fee within the base radius (dollars).
     * @param float $perMile   Surcharge per mile beyond the base radius (dollars).
     *
     * @return float The fee in dollars, rounded to cents.
     *
     * @example
     *   LocalArea::deliveryFee(15, 5, 10, 1); // 20.0
     *   LocalArea::deliveryFee(3,  5, 10, 1); // 10.0  (inside base radius)
     */
    public static function deliveryFee(float $miles, float $baseMiles, float $baseFee, float $perMile): float
    {
        $fee = $baseFee + max(0.0, $miles - $baseMiles) * $perMile;

        return round($fee, 2);
    }

    /**
     * Attach a straight-line distance and estimated delivery fee to each venue.
     *
     * For every venue whose address is present in the coordinate cache, adds a
     * 'miles' key (distance from the studio, rounded to 0.1 mi) and a 'fee' key
     * (estimated delivery fee in dollars). Venues with no known coordinates are
     * returned unchanged, so callers can simply check `isset($venue['miles'])`.
     *
     * @param list<array{name: string, address: string}> $venues  Venues to enrich.
     * @param array<string, array{lat: float, lng: float}> $coords Address→coord cache.
     * @param float $bizLat    Studio latitude.
     * @param float $bizLng    Studio longitude.
     * @param float $baseMiles Base delivery radius (miles).
     * @param float $baseFee   Flat base fee (dollars).
     * @param float $perMile   Per-mile surcharge (dollars).
     *
     * @return list<array{name: string, address: string, miles?: float, fee?: float}>
     *         The venues, each with 'miles' and 'fee' added when coordinates exist.
     *
     * @example
     *   $rich = LocalArea::enrichVenues($venues, LocalArea::coords(), 36.0814, -95.9987, 5, 10, 1);
     *   $rich[0]['fee']; // e.g. 16.0
     */
    public static function enrichVenues(
        array $venues,
        array $coords,
        float $bizLat,
        float $bizLng,
        float $baseMiles,
        float $baseFee,
        float $perMile
    ): array {
        $out = [];
        foreach ($venues as $venue) {
            $coord = $coords[$venue['address']] ?? null;
            if (is_array($coord) && isset($coord['lat'], $coord['lng'])) {
                $miles          = self::haversineMiles($bizLat, $bizLng, (float) $coord['lat'], (float) $coord['lng']);
                $venue['miles'] = round($miles, 1);
                $venue['fee']   = self::deliveryFee($miles, $baseMiles, $baseFee, $perMile);
            }
            $out[] = $venue;
        }

        return $out;
    }

    /**
     * The min/max straight-line distance from the studio to a city's venues.
     *
     * Spans every funeral home and hospital listed for the city (the locations
     * actually delivered to) so the displayed "miles from our shop" range
     * reflects real geocoded distances rather than a hand-entered estimate.
     *
     * @param array<string, mixed>                          $city   A city record.
     * @param array<string, array{lat: float, lng: float}>  $coords Address→coord cache.
     * @param float                                         $bizLat Studio latitude.
     * @param float                                         $bizLng Studio longitude.
     *
     * @return array{min: float, max: float}|null Rounded min/max miles, or null
     *         when none of the city's venues have known coordinates.
     *
     * @example
     *   LocalArea::cityMilesRange($areas['broken-arrow'], LocalArea::coords(), 36.0814, -95.9987);
     *   // ['min' => 8.1, 'max' => 11.7]
     */
    public static function cityMilesRange(array $city, array $coords, float $bizLat, float $bizLng): ?array
    {
        $venues = array_merge(
            $city['funeral_homes'] ?? [],
            $city['hospitals'] ?? [],
        );

        $miles = [];
        foreach ($venues as $venue) {
            $coord = $coords[$venue['address']] ?? null;
            if (is_array($coord) && isset($coord['lat'], $coord['lng'])) {
                $miles[] = self::haversineMiles($bizLat, $bizLng, (float) $coord['lat'], (float) $coord['lng']);
            }
        }

        if ($miles === []) {
            return null;
        }

        return ['min' => round(min($miles), 1), 'max' => round(max($miles), 1)];
    }

    /**
     * The URL path (no language prefix) for a service + city page.
     *
     * @param string               $service  Service code.
     * @param string               $citySlug City slug.
     * @param array<string, mixed> $services Service definitions.
     *
     * @return string e.g. '/funeral-flowers-broken-arrow'. Empty string if the
     *                service code is unknown.
     *
     * @example
     *   LocalArea::path('hospital', 'jenks', $services); // '/hospital-flower-delivery-jenks'
     */
    public static function path(string $service, string $citySlug, array $services): string
    {
        $prefix = $services[$service]['prefix'] ?? null;
        return is_string($prefix) ? '/' . $prefix . '-' . $citySlug : '';
    }

    /**
     * Every service + city path (no language prefix), plus the hub page.
     *
     * Used by the SitemapController to enumerate all landing-page URLs.
     *
     * @param array<string, array<string, mixed>> $areas    City data.
     * @param array<string, array<string, mixed>> $services Service definitions.
     *
     * @return list<string> Paths such as '/delivery-areas',
     *                      '/funeral-flowers-jenks', … in service-then-city order.
     */
    public static function allPaths(array $areas, array $services): array
    {
        $paths = ['/delivery-areas'];
        foreach ($services as $code => $_def) {
            foreach (array_keys($areas) as $slug) {
                $paths[] = self::path($code, $slug, $services);
            }
        }
        return $paths;
    }

    /**
     * Bilingual FAQ items for a service + city, used both as on-page content and
     * as the FAQPage JSON-LD (so the visible text matches the structured data).
     *
     * @param string               $service Service code.
     * @param array<string, mixed> $city    A city record.
     * @param string               $lang    'en' or 'es'.
     *
     * @return list<array{q: string, a: string}> Question/answer pairs.
     */
    public static function faqItems(string $service, array $city, string $lang): array
    {
        $name = (string) $city['name'];
        $es   = self::lang($lang) === 'es';

        $sameDay = $es
            ? "Sí. Para entrega el mismo día en {$name}, haga su pedido temprano; los pedidos de última hora se acomodan según disponibilidad."
            : "Yes. For same-day delivery in {$name}, order early in the day — last-minute orders are accommodated when our schedule allows.";

        $items = [[
            'q' => $es ? "¿Entregan flores en {$name}, OK?" : "Do you deliver flowers in {$name}, OK?",
            'a' => $es
                ? "Sí. Perla's Flowers entrega arreglos hechos a mano en {$name} y en toda el área metropolitana de Tulsa."
                : "Yes. Perla's Flowers delivers locally handcrafted arrangements throughout {$name} and the greater Tulsa metro.",
        ], [
            'q' => $es ? "¿Ofrecen entrega el mismo día en {$name}?" : "Do you offer same-day delivery to {$name}?",
            'a' => $sameDay,
        ]];

        if ($service === 'funeral') {
            $items[] = [
                'q' => $es
                    ? "¿Entregan directamente a las funerarias de {$name}?"
                    : "Can you deliver directly to funeral homes in {$name}?",
                'a' => $es
                    ? "Sí. Coordinamos la entrega con la funeraria según el horario del servicio. Indique el nombre de la funeraria y la fecha y hora del servicio al hacer su pedido."
                    : "Yes. We coordinate delivery with the funeral home around the service time. Just give us the funeral home name and the service date and time when you order.",
            ];
        } elseif ($service === 'hospital') {
            $items[] = [
                'q' => $es
                    ? "¿Entregan a las habitaciones de los pacientes en los hospitales que atienden a {$name}?"
                    : "Do you deliver to patient rooms at hospitals serving {$name}?",
                'a' => $es
                    ? "Entregamos en la recepción del hospital, que lleva las flores a la habitación del paciente. Incluya el nombre completo del paciente y, si lo conoce, el número de habitación."
                    : "We deliver to the hospital's front desk, which routes flowers to the patient's room. Include the patient's full name and room number if you have it.",
            ];
        }

        return $items;
    }

    /**
     * Assemble the schema.org JSON-LD graph for a service + city page.
     *
     * Produces a @graph containing a Service node (provider = the florist,
     * areaServed = the city), a Place node per named venue, and a FAQPage built
     * from {@see self::faqItems()}. The caller json_encodes the result into a
     * <script type="application/ld+json"> block, mirroring ProductController.
     *
     * @param string               $service     Service code.
     * @param array<string, mixed> $city        A city record.
     * @param string               $lang        'en' or 'es'.
     * @param array<string, mixed> $services    Service definitions.
     * @param array{
     *     name?: string, telephone?: string, url?: string,
     *     street?: string, city?: string, state?: string, postal?: string,
     *     pageUrl?: string
     * } $business Business NAP + the absolute URL of this page.
     *
     * @return array<string, mixed> A schema.org graph ready for json_encode().
     *
     * @example
     *   $ld = LocalArea::buildJsonLd('funeral', $bixby, 'en', $services, $biz);
     *   $ld['@graph'][0]['@type']; // 'Service'
     */
    public static function buildJsonLd(
        string $service,
        array $city,
        string $lang,
        array $services,
        array $business
    ): array {
        $cityName = (string) $city['name'];
        $state    = (string) ($city['state'] ?? 'OK');

        $provider = [
            '@type'     => 'Florist',
            'name'      => $business['name'] ?? '',
            'telephone' => $business['telephone'] ?? '',
            'url'       => $business['url'] ?? '',
            'address'   => [
                '@type'           => 'PostalAddress',
                'streetAddress'   => $business['street'] ?? '',
                'addressLocality' => $business['city'] ?? 'Tulsa',
                'addressRegion'   => $business['state'] ?? 'OK',
                'postalCode'      => $business['postal'] ?? '',
                'addressCountry'  => 'US',
            ],
        ];

        $serviceNode = [
            '@type'       => 'Service',
            'serviceType' => (string) ($services[$service]['service_type'] ?? 'Flower delivery'),
            'name'        => self::serviceTitle($service, $city, $lang, $services),
            'provider'    => $provider,
            'areaServed'  => [
                '@type'   => 'City',
                'name'    => $cityName,
                'address' => [
                    '@type'           => 'PostalAddress',
                    'addressLocality' => $cityName,
                    'addressRegion'   => $state,
                    'addressCountry'  => 'US',
                ],
            ],
        ];
        if (!empty($business['pageUrl'])) {
            $serviceNode['url'] = $business['pageUrl'];
        }

        $graph = [$serviceNode];

        foreach (self::venues($service, $city, $services) as $venue) {
            $graph[] = [
                '@type'   => 'Place',
                'name'    => $venue['name'],
                'address' => $venue['address'],
            ];
        }

        $faq = self::faqItems($service, $city, $lang);
        if ($faq !== []) {
            $graph[] = [
                '@type'            => 'FAQPage',
                'mainEntity'       => array_map(static fn (array $f): array => [
                    '@type'          => 'Question',
                    'name'           => $f['q'],
                    'acceptedAnswer' => ['@type' => 'Answer', 'text' => $f['a']],
                ], $faq),
            ];
        }

        return ['@context' => 'https://schema.org', '@graph' => $graph];
    }

    /**
     * Validate a city-data array against the field contract.
     *
     * Checks every city has the required scalar keys, a non-empty direction in
     * both languages, and — for any city — well-formed venue records (each with
     * a non-empty name and an address). Returns a flat list of human-readable
     * problems; an empty list means the data is structurally sound.
     *
     * @param array<string, array<string, mixed>> $areas City data to check.
     *
     * @return list<string> Problems found (empty when valid).
     *
     * @example
     *   LocalArea::validateAreas(LocalArea::areas()); // []  (ships clean)
     */
    public static function validateAreas(array $areas): array
    {
        $problems = [];
        if ($areas === []) {
            return ['areas: file is empty'];
        }

        $required = ['name', 'state', 'distance_miles', 'direction_en', 'direction_es'];

        foreach ($areas as $slug => $city) {
            if (!is_string($slug) || !preg_match('/^[a-z0-9-]+$/', $slug)) {
                $problems[] = "city slug '{$slug}': must match [a-z0-9-]";
            }
            foreach ($required as $key) {
                // Note: a strict '' check (not empty()) so legitimate values like
                // distance_miles '0' for the home city are not falsely rejected.
                if (!self::isFilledString($city[$key] ?? null)) {
                    $problems[] = "city '{$slug}': missing or empty '{$key}'";
                }
            }
            foreach (['funeral_homes', 'hospitals'] as $listKey) {
                $list = $city[$listKey] ?? null;
                if (!is_array($list) || $list === []) {
                    $problems[] = "city '{$slug}': '{$listKey}' must be a non-empty list";
                    continue;
                }
                foreach ($list as $i => $venue) {
                    if (!self::isFilledString($venue['name'] ?? null)) {
                        $problems[] = "city '{$slug}' {$listKey}[{$i}]: missing name";
                    }
                    if (!self::isFilledString($venue['address'] ?? null)) {
                        $problems[] = "city '{$slug}' {$listKey}[{$i}]: missing address";
                    }
                }
            }
        }

        return $problems;
    }

    /**
     * Validate a service-definition array against the field contract.
     *
     * @param array<string, array<string, mixed>> $services Service definitions.
     *
     * @return list<string> Problems found (empty when valid).
     */
    public static function validateServices(array $services): array
    {
        $problems = [];
        if ($services === []) {
            return ['services: file is empty'];
        }

        $required = [
            'prefix', 'service_type', 'label_en', 'label_es',
            'title_en', 'title_es', 'meta_en', 'meta_es', 'h1_en', 'h1_es',
        ];

        foreach ($services as $code => $def) {
            foreach ($required as $key) {
                if (!self::isFilledString($def[$key] ?? null)) {
                    $problems[] = "service '{$code}': missing or empty '{$key}'";
                }
            }
            // 'entities', when present, must be a key that exists on city records.
            $entities = $def['entities'] ?? null;
            if ($entities !== null && !in_array($entities, ['funeral_homes', 'hospitals'], true)) {
                $problems[] = "service '{$code}': 'entities' must be null, 'funeral_homes', or 'hospitals'";
            }
        }

        return $problems;
    }

    /**
     * Normalize a language code to the supported set, defaulting to English.
     *
     * @param string $lang Raw language code.
     *
     * @return string 'en' or 'es'.
     */
    private static function lang(string $lang): string
    {
        return $lang === 'es' ? 'es' : 'en';
    }

    /**
     * Whether a value is a non-empty string. Used instead of empty() so that
     * legitimate values such as the string '0' are not treated as missing.
     *
     * @param mixed $value The value to test.
     *
     * @return bool True only for a string that is not ''.
     */
    private static function isFilledString(mixed $value): bool
    {
        return is_string($value) && $value !== '';
    }

    /**
     * Substitute the city name into a single-%s template, tolerating templates
     * that (incorrectly) contain no placeholder.
     *
     * @param string $template A template with at most one %s.
     * @param string $cityName The city display name.
     *
     * @return string The filled string.
     */
    private static function fill(string $template, string $cityName): string
    {
        if (!str_contains($template, '%s')) {
            return $template;
        }
        return sprintf($template, $cityName);
    }
}
