<?php

declare(strict_types=1);

/**
 * Geocoded coordinates for local-area venues — address => [lat, lng].
 *
 * GENERATED by bin/geocode-local-areas.php. Do not edit by hand; re-run the
 * script after changing venue addresses in config/local-areas.php.
 *
 * @return array<string, array{lat: float, lng: float}>
 */

return [
    '1000 W Boise Cir, Broken Arrow, OK 74012' => ['lat' => 36.077939, 'lng' => -95.799096],
    '1004 E Bryan Ave, Sapulpa, OK 74066' => ['lat' => 35.993248, 'lng' => -96.100843],
    '10501 E 91st St S, Tulsa, OK 74133' => ['lat' => 36.031983, 'lng' => -95.859093],
    '1112 S Boston Ave, Tulsa, OK 74119' => ['lat' => 36.145963, 'lng' => -95.985854],
    '1120 S Utica Ave, Tulsa, OK 74104' => ['lat' => 36.060372, 'lng' => -95.966138],
    '1200 N Cleveland Ave, Sand Springs, OK 74063' => ['lat' => 36.150492, 'lng' => -96.114231],
    '1208 S Main St, Sapulpa, OK 74066' => ['lat' => 35.984685, 'lng' => -96.113652],
    '1329 E 151st St S, Glenpool, OK 74033' => ['lat' => 35.944286, 'lng' => -96.007170],
    '13307 S Memorial Dr, Bixby, OK 74008' => ['lat' => 35.969918, 'lng' => -95.886540],
    '1402 S Boulder Ave, Tulsa, OK 74119' => ['lat' => 36.142337, 'lng' => -95.988544],
    '1660 S Elm Pl, Broken Arrow, OK 74012' => ['lat' => 36.036160, 'lng' => -95.797591],
    '1908 S Memorial Dr, Tulsa, OK 74112' => ['lat' => 36.135339, 'lng' => -95.886702],
    '1923 S Utica Ave, Tulsa, OK 74104' => ['lat' => 36.134618, 'lng' => -95.967153],
    '202 E Oak St, Catoosa, OK 74015' => ['lat' => 36.184806, 'lng' => -95.745305],
    '211 E Broadway St, Sand Springs, OK 74063' => ['lat' => 36.139757, 'lng' => -96.107403],
    '222 W Broadway Ave, Broken Arrow, OK 74012' => ['lat' => 36.052449, 'lng' => -95.792407],
    '3000 S Elm Pl, Broken Arrow, OK 74012' => ['lat' => 36.021323, 'lng' => -95.797520],
    '3612 E 91st St, Tulsa, OK 74137' => ['lat' => 36.031841, 'lng' => -95.936815],
    '3841 S Peoria Ave, Tulsa, OK 74105' => ['lat' => 36.106814, 'lng' => -95.975632],
    '3959 E 31st St, Tulsa, OK 74135' => ['lat' => 36.118874, 'lng' => -95.932608],
    '4 W 41st St, Sand Springs, OK 74063' => ['lat' => 36.104624, 'lng' => -96.119017],
    '400 E Teel Rd, Sapulpa, OK 74067' => ['lat' => 35.975401, 'lng' => -96.105627],
    '4161 E Admiral Pl, Tulsa, OK 74115' => ['lat' => 36.160767, 'lng' => -95.925274],
    '4170 E Admiral Pl, Tulsa, OK 74115' => ['lat' => 36.160694, 'lng' => -95.930272],
    '5757 S Memorial Dr, Tulsa, OK 74145' => ['lat' => 36.081374, 'lng' => -95.886399],
    '6161 S Yale Ave, Tulsa, OK 74136' => ['lat' => 36.075073, 'lng' => -95.922069],
    '6500 S 129th E Ave, Broken Arrow, OK 74012' => ['lat' => 36.073058, 'lng' => -95.833203],
    '6521 E 151st St S, Bixby, OK 74008' => ['lat' => 35.944794, 'lng' => -95.904181],
    '744 W 9th St, Tulsa, OK 74127' => ['lat' => 36.146906, 'lng' => -95.999999],
    '804 E Taft Ave Ste E, Sapulpa, OK 74066' => ['lat' => 35.988311, 'lng' => -96.102954],
    '815 W Main St, Jenks, OK 74037' => ['lat' => 36.023455, 'lng' => -95.979184],
    '8801 S 101st E Ave, Tulsa, OK 74133' => ['lat' => 36.035358, 'lng' => -95.864769],
    '9350 E 51st St, Tulsa, OK 74145' => ['lat' => 36.089905, 'lng' => -95.872643],
    '9761 E 31st St, Tulsa, OK 74146' => ['lat' => 36.119044, 'lng' => -95.864641],
];
