<?php

declare(strict_types=1);

/**
 * Local service-area data powering the city landing pages (funeral / hospital /
 * birthday flower delivery). Consumed by App\Support\LocalArea, the
 * LocalAreaController, and the SitemapController.
 *
 * The array is keyed by city slug (the value captured by the
 * /funeral-flowers-{city} family of routes). Each entry describes one city
 * Perla's Flowers delivers to, plus the named local funeral homes and
 * hospitals that make the pages rank for "flowers for [specific venue]"
 * searches.
 *
 * Field contract (enforced by App\Support\LocalArea::validateAreas and the
 * LocalAreasIntegrityTest):
 *   - name           string  Display name of the city.
 *   - state          string  Two-letter state code.
 *   - distance_miles string  Approx. distance range from the studio ('0' = home).
 *   - direction_en   string  English "how to get there from Tulsa" blurb.
 *   - direction_es   string  Spanish equivalent of direction_en.
 *   - zips           list<string>            Representative ZIP codes.
 *   - funeral_homes  list<array{name,address}> Named local funeral homes.
 *   - hospitals      list<array{name,address}> Named hospitals serving the city.
 *
 * Venue lists are language-neutral (proper nouns + postal addresses). The
 * straight-line distance from the studio to each venue — and the estimated
 * delivery fee — is computed at render time from per-venue coordinates in
 * config/local-areas-coords.php (generated by bin/geocode-local-areas.php),
 * using the same Haversine + fee math as the order form. See
 * App\Support\LocalArea::enrichVenues / deliveryFee.
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │ DRAFT DATA — VERIFY BEFORE DEPLOY.                                        │
 * │ Names/addresses were compiled from public web sources (June 2026) and    │
 * │ MUST be confirmed against Google Business Profiles / the businesses      │
 * │ themselves before going live. The named-entity match is the entire SEO   │
 * │ strategy, so an outdated address actively hurts. Cities without their    │
 * │ own hospital list the nearest facilities senders actually target. The    │
 * │ delivery_miles values are estimates; the final fee is calculated from    │
 * │ the real delivery address at checkout.                                    │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * @return array<string, array{
 *     name: string, state: string, distance_miles: string,
 *     direction_en: string, direction_es: string, zips: list<string>,
 *     funeral_homes: list<array{name: string, address: string}>,
 *     hospitals: list<array{name: string, address: string}>
 * }>
 */

return [

    'tulsa' => [
        'name'           => 'Tulsa',
        'state'          => 'OK',
        'distance_miles' => '0',
        'direction_en'   => 'our home city — same-day delivery across the Tulsa metro',
        'direction_es'   => 'nuestra ciudad — entrega el mismo día en toda el área metropolitana de Tulsa',
        'zips'           => ['74104', '74105', '74114', '74133', '74135', '74136', '74145'],
        'funeral_homes'  => [
            ['name' => "Stanleys Funeral & Cremation Service",          'address' => '3959 E 31st St, Tulsa, OK 74135'],
            ['name' => "Moore's Eastlawn Funeral Home",                 'address' => '1908 S Memorial Dr, Tulsa, OK 74112'],
            ['name' => "Moore's Southlawn Funeral Home",                'address' => '9350 E 51st St, Tulsa, OK 74145'],
            ['name' => "Ninde Funeral & Cremation (Brookside)",         'address' => '3841 S Peoria Ave, Tulsa, OK 74105'],
            ['name' => "Schaudt's Tulsa Funeral Service & Cremation",   'address' => '5757 S Memorial Dr, Tulsa, OK 74145'],
            ['name' => "Fitzgerald Southwood Colonial Chapel",          'address' => '3612 E 91st St, Tulsa, OK 74137'],
            ['name' => "Fitzgerald Ivy Chapel",                         'address' => '1402 S Boulder Ave, Tulsa, OK 74119'],
            ['name' => "Rose Hill Funeral Home and Memorial Park",      'address' => '4161 E Admiral Pl, Tulsa, OK 74115'],
            ['name' => "Serenity Funerals and Crematory",               'address' => '4170 E Admiral Pl, Tulsa, OK 74115'],
            ['name' => "Gary Kelley's Add'Vantage Funeral Service",     'address' => '9761 E 31st St, Tulsa, OK 74146'],
            ['name' => "Simplicity Burial Co & Oklahoma Cremation",     'address' => '1112 S Boston Ave, Tulsa, OK 74119'],
        ],
        'hospitals'      => [
            ['name' => 'Saint Francis Hospital',            'address' => '6161 S Yale Ave, Tulsa, OK 74136'],
            ['name' => 'Ascension St. John Medical Center', 'address' => '1923 S Utica Ave, Tulsa, OK 74104'],
            ['name' => 'Hillcrest Medical Center',          'address' => '1120 S Utica Ave, Tulsa, OK 74104'],
            ['name' => 'OSU Medical Center',                'address' => '744 W 9th St, Tulsa, OK 74127'],
            ['name' => 'Saint Francis Hospital South',      'address' => '10501 E 91st St S, Tulsa, OK 74133'],
            ['name' => 'Hillcrest Hospital South',          'address' => '8801 S 101st E Ave, Tulsa, OK 74133'],
        ],
    ],

    'jenks' => [
        'name'           => 'Jenks',
        'state'          => 'OK',
        'distance_miles' => '4–6',
        'direction_en'   => 'just across the Arkansas River southwest of Tulsa',
        'direction_es'   => 'justo al otro lado del río Arkansas, al suroeste de Tulsa',
        'zips'           => ['74037'],
        'funeral_homes'  => [
            ['name' => 'Hargrove-Marker Funeral & Cremation Services', 'address' => '815 W Main St, Jenks, OK 74037'],
        ],
        'hospitals'      => [
            ['name' => 'Saint Francis Hospital South', 'address' => '10501 E 91st St S, Tulsa, OK 74133'],
            ['name' => 'Saint Francis Hospital',       'address' => '6161 S Yale Ave, Tulsa, OK 74136'],
        ],
    ],

    'broken-arrow' => [
        'name'           => 'Broken Arrow',
        'state'          => 'OK',
        'distance_miles' => '8–11',
        'direction_en'   => 'directly east of Tulsa via the Broken Arrow Expressway (OK-51)',
        'direction_es'   => 'directamente al este de Tulsa por la Broken Arrow Expressway (OK-51)',
        'zips'           => ['74011', '74012', '74014'],
        'funeral_homes'  => [
            ['name' => 'Floral Haven Funeral Home & Crematory', 'address' => '6500 S 129th E Ave, Broken Arrow, OK 74012'],
            ['name' => 'Hayhurst Funeral Home',                 'address' => '1660 S Elm Pl, Broken Arrow, OK 74012'],
            ['name' => 'Garrett Funeral Home',                  'address' => '222 W Broadway Ave, Broken Arrow, OK 74012'],
        ],
        'hospitals'      => [
            ['name' => 'Saint Francis Hospital Broken Arrow', 'address' => '3000 S Elm Pl, Broken Arrow, OK 74012'],
            ['name' => 'Ascension St. John Broken Arrow',     'address' => '1000 W Boise Cir, Broken Arrow, OK 74012'],
            ['name' => 'Hillcrest Hospital South',            'address' => '8801 S 101st E Ave, Tulsa, OK 74133'],
        ],
    ],

    'bixby' => [
        'name'           => 'Bixby',
        'state'          => 'OK',
        'distance_miles' => '9–12',
        'direction_en'   => 'straight south of Tulsa down S Peoria Ave or Memorial Drive',
        'direction_es'   => 'directo al sur de Tulsa por S Peoria Ave o Memorial Drive',
        'zips'           => ['74008'],
        'funeral_homes'  => [
            ['name' => 'Leonard-Marker Funeral Home',          'address' => '6521 E 151st St S, Bixby, OK 74008'],
            ['name' => 'Bixby-South Tulsa Funeral Service',     'address' => '13307 S Memorial Dr, Bixby, OK 74008'],
        ],
        'hospitals'      => [
            ['name' => 'Saint Francis Hospital South', 'address' => '10501 E 91st St S, Tulsa, OK 74133'],
            ['name' => 'Hillcrest Hospital South',     'address' => '8801 S 101st E Ave, Tulsa, OK 74133'],
        ],
    ],

    'glenpool' => [
        'name'           => 'Glenpool',
        'state'          => 'OK',
        'distance_miles' => '11–13',
        'direction_en'   => 'directly south of Tulsa down US-75',
        'direction_es'   => 'directamente al sur de Tulsa por la US-75',
        'zips'           => ['74033'],
        'funeral_homes'  => [
            ['name' => "Schaudt's Glenpool-Bixby Funeral Service & Cremation Care", 'address' => '1329 E 151st St S, Glenpool, OK 74033'],
        ],
        'hospitals'      => [
            ['name' => 'Saint Francis Hospital South', 'address' => '10501 E 91st St S, Tulsa, OK 74133'],
            ['name' => 'Ascension St. John Sapulpa',   'address' => '1004 E Bryan Ave, Sapulpa, OK 74066'],
        ],
    ],

    'sapulpa' => [
        'name'           => 'Sapulpa',
        'state'          => 'OK',
        'distance_miles' => '12–14',
        'direction_en'   => 'south-southwest of Tulsa on I-44 West',
        'direction_es'   => 'al sur-suroeste de Tulsa por la I-44 Oeste',
        'zips'           => ['74066', '74067'],
        'funeral_homes'  => [
            ['name' => 'Green Hill Funeral Home',                    'address' => '400 E Teel Rd, Sapulpa, OK 74067'],
            ['name' => 'Smith Family Funeral Home',                  'address' => '1208 S Main St, Sapulpa, OK 74066'],
            ['name' => 'Traditions Funeral and Cremation Services',  'address' => '804 E Taft Ave Ste E, Sapulpa, OK 74066'],
        ],
        'hospitals'      => [
            ['name' => 'Ascension St. John Sapulpa', 'address' => '1004 E Bryan Ave, Sapulpa, OK 74066'],
            ['name' => 'Saint Francis Hospital',     'address' => '6161 S Yale Ave, Tulsa, OK 74136'],
        ],
    ],

    'catoosa' => [
        'name'           => 'Catoosa',
        'state'          => 'OK',
        'distance_miles' => '13–15',
        'direction_en'   => 'northeast of Tulsa on I-44 East toward the Hard Rock Casino area',
        'direction_es'   => 'al noreste de Tulsa por la I-44 Este, hacia la zona del Hard Rock Casino',
        'zips'           => ['74015'],
        'funeral_homes'  => [
            ['name' => 'Rice Funeral Service & Cremation Care', 'address' => '202 E Oak St, Catoosa, OK 74015'],
        ],
        'hospitals'      => [
            ['name' => 'Ascension St. John Medical Center', 'address' => '1923 S Utica Ave, Tulsa, OK 74104'],
            ['name' => 'Hillcrest Medical Center',          'address' => '1120 S Utica Ave, Tulsa, OK 74104'],
        ],
    ],

    'sand-springs' => [
        'name'           => 'Sand Springs',
        'state'          => 'OK',
        'distance_miles' => '14–15',
        'direction_en'   => 'west-northwest of Tulsa via I-244 West or US-412',
        'direction_es'   => 'al oeste-noroeste de Tulsa por la I-244 Oeste o la US-412',
        'zips'           => ['74063'],
        'funeral_homes'  => [
            ['name' => 'Mark Griffith Memorial Funeral Home — Riverside Chapel', 'address' => '4 W 41st St, Sand Springs, OK 74063'],
            ['name' => 'Mobley-Groesbeck Funeral Service',                       'address' => '211 E Broadway St, Sand Springs, OK 74063'],
            ['name' => 'Dillon Funeral Services',                                'address' => '1200 N Cleveland Ave, Sand Springs, OK 74063'],
        ],
        'hospitals'      => [
            ['name' => 'OSU Medical Center',                'address' => '744 W 9th St, Tulsa, OK 74127'],
            ['name' => 'Ascension St. John Medical Center', 'address' => '1923 S Utica Ave, Tulsa, OK 74104'],
            ['name' => 'Hillcrest Medical Center',          'address' => '1120 S Utica Ave, Tulsa, OK 74104'],
        ],
    ],

];
